version: "2"

services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - /opt/docker/sonar/sonarqube_conf:/opt/sonarqube/conf
      - /opt/docker/sonar/sonarqube_data:/opt/sonarqube/data
      - /opt/docker/sonar/sonarqube_extensions:/opt/sonarqube/extensions
      - /opt/docker/sonar/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /opt/docker/sonar/postgresql:/var/lib/postgresql
      - /opt/docker/sonar/postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge
