version: "3"

services:
  postgres:
    container_name: postgres-sonar
    image: postgres:9-alpine
    ports:
      - "5432:5432"
    networks:
      - sonarnet
    environment:
      - POSTGRES_DB=sonar
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar

  sonarqube:
    depends_on:
      - postgres
    container_name: sonarqube
    image: sonarqube:lts
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar

networks:
  sonarnet:
    driver: bridge
